[workspace]
resolver = "3"
members = [
  "hibp-bin-fetch",
  "hibp-profiler",
  "hibp-verifier",
]

[workspace.dependencies]
hibp-bin-fetch = { path = "hibp-bin-fetch" }
hibp-verifier = { path = "hibp-verifier" }
